- Add support for 'status' in the init.d (Closes: #514721)   - Use 'cron' instead of 'crond' (Closes: #497699)

diff --git a/debian/cron.init b/debian/cron.init
--- a/debian/cron.init
+++ b/debian/cron.init
@@ -50,24 +50,39 @@ fi
 
 
 case "$1" in
-start)	log_daemon_msg "Starting periodic command scheduler" "crond"
+start)	log_daemon_msg "Starting periodic command scheduler" "cron"
         start-stop-daemon --start --quiet --pidfile $PIDFILE --name cron --startas /usr/sbin/cron -- $LSBNAMES $EXTRA_OPTS
         log_end_msg $?
 	;;
-stop)	log_daemon_msg "Stopping periodic command scheduler" "crond"
+stop)	log_daemon_msg "Stopping periodic command scheduler" "cron"
         start-stop-daemon --stop --quiet --pidfile $PIDFILE --name cron
         log_end_msg $?
         ;;
-restart) log_daemon_msg "Restarting periodic command scheduler" "crond" 
+restart) log_daemon_msg "Restarting periodic command scheduler" "cron" 
         start-stop-daemon --stop --retry 5 --quiet --pidfile $PIDFILE --name cron
         start-stop-daemon --start --quiet --pidfile $PIDFILE --name cron --startas /usr/sbin/cron -- $LSBNAMES $EXTRA_OPTS
         log_end_msg $?
         ;;
-reload|force-reload) log_daemon_msg "Reloading configuration files for periodic command scheduler" "crond"
+reload|force-reload) log_daemon_msg "Reloading configuration files for periodic command scheduler" "cron"
 	# cron reloads automatically
         log_end_msg 0
         ;;
-*)	log_action_msg "Usage: /etc/init.d/cron {start|stop|restart|reload|force-reload}"
+status)
+       log_action_begin_msg "Checking periodic command scheduler"
+       if pidofproc -p "$PIDFILE" >/dev/null; then
+            log_action_end_msg 0 "running"
+            exit 0
+       else
+           if [ -e "$PIDFILE" ]; then
+                log_action_end_msg 1 "failed to start"
+                exit 1
+           else
+                log_action_end_msg 0 "not running"
+                exit 3
+           fi
+       fi
+         ;;
+*)	log_action_msg "Usage: /etc/init.d/cron {start|stop|status|restart|reload|force-reload}"
         exit 2
         ;;
 esac
